name: MessengerMonitorBundle CI

on:
  pull_request: ~
  push:
    branches:
      - "master"

jobs:
  coding-standards:
    name: "Coding Standards"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php:
          - "8.0"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Set up PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php }}

      - name: "Install dependencies with composer"
        uses: ramsey/composer-install@v2

      - name: "Run friendsofphp/php-cs-fixer"
        run: vendor/bin/php-cs-fixer fix --ansi --config=.php-cs-fixer.dist.php --diff --dry-run --verbose

  static-code-analysis:
    name: "Static Code Analysis"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php:
          - "8.0"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Set up PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php }}

      - name: "Install dependencies with composer"
        uses: ramsey/composer-install@v2

      - name: "Run vimeo/psalm"
        run: vendor/bin/psalm --diff --show-info=false --stats --threads=4

  tests-mariadb:
    name: "Tests with MariaDB"

    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        php:
          - "8.0"
          - "8.1"
        dependencies:
          - "lowest"
          - "highest"

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: messenger_monitor_bundle_test
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Set up PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php }}

      - name: "Install dependencies with composer"
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: "Unit Tests"
        run: vendor/bin/simple-phpunit
        env:
          TEST_DATABASE_DSN: mysql://root:password@127.0.0.1:${{ job.services.mariadb.ports[3306] }}/messenger_monitor_bundle_test

  tests-postgres:
    name: "Tests with PostgreSQL"

    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        php:
          - "8.0"
          - "8.1"
        postgres-version:
          - "14"

    services:
      postgres:
        image: "postgres:${{ matrix.postgres-version }}"
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: messenger_monitor_bundle_test
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        options: --health-cmd "pg_isready -U user" --health-interval 1s --health-timeout 5s --health-retries 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Set up PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php }}

      - name: "Install dependencies with composer"
        uses: ramsey/composer-install@v2

      - name: "Unit Tests"
        run: vendor/bin/simple-phpunit
        env:
          TEST_DATABASE_DSN: postgres://user:password@127.0.0.1:${{ job.services.postgres.ports[5432] }}/messenger_monitor_bundle_test
