name: MessengerMonitorBundle CI
on:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  coding-standards:
    name: "Coding Standards"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php:
          - "8.0"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Set up PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php }}

      - name: "Install dependencies with composer"
        uses: ramsey/composer-install@v2

      - name: "Run friendsofphp/php-cs-fixer"
        run: vendor/bin/php-cs-fixer fix --ansi --config=.php-cs-fixer.dist.php --diff --dry-run --verbose

  build:
    name: "Unit Tests"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.0'
          - php: '8.1'
          - php: '8.0'
            mode: low-deps
          - php: '8.1'
            mode: low-deps
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: messenger_monitor_bundle_test
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Verify MariaDB connection
        env:
          PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done

      - name: Install dependencies
        run: |
          if [[ "${{ matrix.mode }}" = low-deps ]]; then
              COMPOSER_OPTION="--prefer-lowest"
          fi

          composer update --prefer-dist --no-progress ${COMPOSER_OPTION:=""}

      - name: Psalm Static Analysis
        run: vendor/bin/psalm -c psalm.xml

      - name: Unit Tests
        run: vendor/bin/simple-phpunit
        if: always()
        env:
          TEST_DATABASE_DSN: mysql://root:password@127.0.0.1:${{ job.services.mariadb.ports[3306] }}/messenger_monitor_bundle_test
