name: MessengerMonitorBundle CI
on:
  pull_request: ~
  push:
    branches:
      - master
jobs:
  build:
    name: MessengerMonitor
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: [ 8.0, 8.1 ]
        symfony-versions: [ 5.4, 6.0 ]
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: messenger_monitor_bundle_test
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: php-cs-fixer

      - name: Verify MariaDB connection
        env:
          PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done

      - name: Install dependencies
        run: |
          if [ "${SF_VERSION}" = "5.4" ]; then
            COMPOSER_OPTION="--prefer-lowest"
          fi

          composer update --prefer-dist --no-progress ${COMPOSER_OPTION:=""}
        env:
          SF_VERSION: ${{ matrix.symfony-versions }}

      - name: Check src with php-cs-Fixer
        run: php-cs-fixer fix --diff --dry-run

      - name: Psalm Static Analysis
        run: vendor/bin/psalm -c psalm.xml
        if: always()

      - name: Unit Tests
        run: vendor/bin/simple-phpunit
        if: always()
        env:
          TEST_DATABASE_DSN: mysql://root:password@127.0.0.1:${{ job.services.mariadb.ports[3306] }}/messenger_monitor_bundle_test
