name: MessengerMonitorBundle CI
on: [push, pull_request]
jobs:
    build:
        name: MessengerMonitor
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php-versions: ['7.2', '7.3', '7.4']
        steps:
            - name: Checkout
              uses: actions/checkout@v2.0.0

            - name: Get Composer Cache Directory
              id: composer-cache
              run: |
                  echo "::set-output name=dir::$(composer config cache-files-dir)"
            - uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-
            - name: Install dependencies
              if: steps.composer-cache.outputs.cache-hit != 'true'
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Psalm Static Analysis
              run: vendor/bin/psalm -c psalm.xml

            - name: Unit Tests
              run: vendor/bin/simple-phpunit
              if: always()
